WC1/Controllers/FeedReaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using WC1.Models;
using WC1.Services.Realisation;

namespace WC1.Controllers
{
  public class FeedReaderController : Controller
  {
    private readonly FeedReaderService feedReaderService = new FeedReaderService();
    // GET: /FeedReader/
    public ActionResult Index()
    {
      var model = feedReaderService.GetScoreFeed();
      return View(model);
    }
  }
}

WC1/Controllers/FixtureController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using WC1.Services.Realisation;
using WC1.ViewModels;
using WC1.ViewModels.BettingOptions;

namespace WC1.Controllers
{
  public class FixtureController : Controller
  {
    private readonly FixtureService fixtureService = new FixtureService();
    // GET: /Fixtures/
    public ActionResult Index()
    {
      var model = fixtureService.GetAllFixtures();
      return View(model);
    }

    public ViewResult Details(int fixtureID)
    {
      ViewBag.FixtureID = fixtureID;
      var model = fixtureService.GetFixtureDetails(fixtureID);
      return View();
    }
    
  }
}

WC1/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WC1.Models;

namespace WC1.Controllers
{
    public class TeamController : Controller
    {
        readonly WcDbContext dbContext = new WcDbContext();
        //
        // GET: /Team/
        public ActionResult Index()
        {
          return View(dbContext.Teams);
        }
    }
}

WC1/Views/Shared/ResultPartial.cshtml
@model WC1.ViewModels.BettingOptions.BettingViewModel
@{
    ViewBag.Title = "Betting Options";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm(new {ViewBag.ReturnUrl}))
{
    @Html.ValidationSummary(true)
        <div class="panel panel-group" id="accordion">
            @foreach (var m in Model.AllViewModel)
            {
                 @Html.EditorFor(vm => m, m.ViewName);
            }
        </div>
    <input type="submit" class="btn btn-info btn-default" value="Place Bet"/>
       @Html.HiddenFor( m => m.FixtureID)
}

WC1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @*@Scripts.Render("~/bundles/bootstrap")*@
    </head>
    <header class="page-header">
        <ul class="nav nav-pills">
            <li role="presentation" class="active">@Html.ActionLink("Home", "Index", "Fixture", new {area =""}, null)</li>
            <li role="presentation">@Html.ActionLink("Profile","MyProfile", "Prediction", new {profileID =1, area = "Profile"}, null)</li>
            <li role="presentation"><a href="#">Messages</a></li>
            <li role="presentation">@Html.ActionLink("Teams","Index", "Team", new {area =""}, null)</li>
            <li role="presentation">@Html.ActionLink("Feeds","Index", "FeedReader", new {area=""}, null)</li>
            <li role="presentation">@Html.ActionLink("Rules","Index", "Rules", new {area=""}, null)</li>
            <li role="presentation">@Html.ActionLink("Admin","Index", "Admin", new {area="Admin"}, null)</li>
        </ul>
    </header>
    <body class="modal-body">
        @RenderBody()

        @RenderSection("scripts", required: false)
    </body>
    <footer style="padding-top: 60px;" class="text-center text-info">@@Registered Company. 2015</footer>
</html>